# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - echo "BacDive_email=$ID" > ~/.Renviron
  - echo "BacDive_password=$PW" >> ~/.Renviron
